### ISSUE TITLE
[Bug]: Literal mustache syntax getting truncated in API request

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#10489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've got a TextWidget with `text` property value as follows:
```
name: "Abcd"
age: 12
templates:
    - en: "Hello {{"{{ name }}"}}"
    - fr: "Bonjour {{"{{ name }}"}}"
```

Since there's a literal mustache syntax, I've disabled "Smart JSON substitution" as well.
I'm sending it to an API via POST method with the data as follows:
```
{
	content: {{input1.text}}
}
```

In the API end, what I receive is a truncated value:
```
name: "Abcd"
age: 12
templates:
    - en: "Hello {{name
```

### Steps To Reproduce

Do the steps shown in the above description

### Environment

Production

### Version

Cloud
