### ISSUE TITLE
[Bug]: If MongoDB user doesn't have permissions to see replicaset status, server doesn't start

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#11418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, we check if replicaset is enabled on the external MongoDB, and if not, we exit and the fat container doesn't start.

But if replicaset is enabled, but the user being used doesn't have permission to do `rs.status()`, this failure is a false-positive.

So, can we check if we have the admin or just `clusterMonitor` role before doing the check? If we don't have permission to do so, can we try an alternate method to see if replicaset is enabled? Like, checking if the `changeStream` API is working? Or worst case, just print a warning message that we couldn't check for replicaset configuration on the MongoDB server?

### Steps To Reproduce

1. Start up Appsmith fat container.
2. Connect it with an external MongoDB database, but use a user credential that's not an admin, and has just read/write permissions on the database and nothing else.
3. Try to restart the container.

You'll see the following error and the container won't start.

```
appsmith-ce    | ********************************************************************
appsmith-ce    | *          Mongodb cloud replica set is not enabled                *
appsmith-ce    | ********************************************************************
appsmith-ce exited with code 1
```

### Environment

Production

### Version

Self-Hosted

**Comment by MichaelLeeHobbs** [comment]
[appsmith](https://github.com/appsmithorg/appsmith/tree/7a950004db2f46ce3ff0db162f7b3382947bc219)/[deploy](https://github.com/appsmithorg/appsmith/tree/7a950004db2f46ce3ff0db162f7b3382947bc219/deploy)/[docker](https://github.com/appsmithorg/appsmith/tree/7a950004db2f46ce3ff0db162f7b3382947bc219/deploy/docker)/entrypoint.sh 
There is a bug on line 125

```
  if [[ $isUriLocal -gt 0 ]]; then
```

Should be

```
  if [[ $isUriLocal -eq 0 ]]; then
```

**Comment by MichaelLeeHobbs** [comment]
I have confirmed this is the fix. Here is a work around example.

In the compose file add a volume `- ./patch/entrypoint.sh:/opt/appsmith/entrypoint.sh`
```
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    restart: always
    env_file: env/appsmith.dev.env
#    entrypoint: 'sleep 500'
    ports:
      - "9001:9001"
    volumes:
      - appsmith:/appsmith-stacks
      - ./patch/entrypoint.sh:/opt/appsmith/entrypoint.sh
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      - db
      - web

```

Create a patch directory and add the [entrypoint.sh](https://github.com/appsmithorg/appsmith/blob/7a950004db2f46ce3ff0db162f7b3382947bc219/deploy/docker/entrypoint.sh)
Modify the entrypoint.sh file line 125 to `if [[ $isUriLocal -eq 0 ]]; then` ie change the `gt` to `eq` then reploy the stack.
