### ISSUE TITLE
[Feature]: Support getting values from secrets in Helm chart configuration

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#11752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, when deploying Appsmith with Helm charts, all configuration values should be given in plain-text in the `values.yaml` file. This includes sensitive values like MonogDB connection URI, which would include the password.

Instead, the Helm charts should support getting these values from secrets and support this in a backward-compatible way.

For example, today, we can set the MongoDB URI, like the following:

```yaml
applicationConfig:
  APPSMITH_MONGODB_URI: "mongodb-uri-here"
```

In addition to this, we should support something like this:

```yaml
applicationConfig:
  APPSMITH_MONGODB_URI:
    secretName: "appsmith-secrets"
    secretKey: "mongodb-uri"
```

When configured this way, the Helm chart should just pick the MongoDB URI from this secret. This secret can be created separately by the users within the same namespace as Appsmith, by creating a resource like:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: appsmith-secrets
type: Opaque
data:
  mongodb-uri: bW9uZ291c2Vy
```

### Why should this be worked on?

This will allow the `values.yaml` file to not contain sensitive values directly, and be able to safely share in a git repo.
