### ISSUE TITLE
[Bug]: Appsmith behind Caddy in Docker Compose with Custom SSL not working

### ISSUE THREAD

**Issue by nzpopa** [appsmithorg/appsmith#13783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm using caddy-docker-proxy (https://github.com/lucaslorentz/caddy-docker-proxy) for auto SSL and to reverse proxy traffic for all my docker containers. 

This is my Appsmith docker-compose.yaml:

```
version: "3"

networks:
  caddy:
    external: true

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    labels:
      caddy: appsmith.something.com
      caddy.reverse_proxy: "{{ upstreams https }}"
    environment:
      - APPSMITH_CUSTOM_DOMAIN=appsmith.something.com
    networks:
      - caddy
    expose:
      - "80"
      - "443"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
```

I have created an A record pointing appsmith.something.com to my IP address.
Because I'm using Caddy in this manner (reverse proxy and auto SSL), then Appsmith's internal letsencrypt will fail to confirm the acme challenge. Reading the docs (https://docs.appsmith.com/setup/instance-configuration/custom-domain#custom-ssl-certificate), I followed the steps to install a custom ssl certificate.

I copied appsmith.crt and appsmith.key from caddy volume to ssl/cert.pem and ssl/privkey.pem, but I get a 502 bad gateway response, which usually happens if the container fails to properly start its services. 

This is the log:

https://gist.github.com/nzpopa/7737f02224289cabe792f3b6698671f5

### Steps To Reproduce

1. Install caddy-docker-proxy using docker compose
2. Copy my docker-compose.yaml
3. Run docker compose up -d
4. Copy the certs from caddy-docker-proxy volume to appsmith/stacks/ssl and rename them as instructed in the docs

### Version

Latest self-hosted
