### ISSUE TITLE
[Bug]: Port not included on login

### ISSUE THREAD

**Issue by disl-pdavid** [appsmithorg/appsmith#14505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Running locally on docker and using a different port in my docker-compose.yml:

```
services:
  appsmith:
    image: appsmith/appsmith-ce:latest
    container_name: appsmith
    ports:
      - "8080:80"
      - "443:443"
```

Everything works fine but during the login after submitting the Email/Password I get redirected to localhost/applications (w/o the port).  Either manually adding the port or going back will load the correct page at that point.

### Steps To Reproduce

1. Docker install - use port 8080 on the host to 80 in the container (see above).
2. Login with credentials.
3. Get redirected to the page w/o the port. :(

### Version

Self-hosted 1.7.1
