### ISSUE TITLE
[Bug]: Api call returns Execution failed with status 5000 Unknown host.

### ISSUE THREAD

**Issue by alanPaivaAsp** [appsmithorg/appsmith#14754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I just downloaded the docker-compose file, listed in this tutorial https://docs.appsmith.com/setup/docker, then after docker-compose up everything seems just fine (after changing exposed port to 8081):
![image](https://user-images.githubusercontent.com/22459531/175135423-9d6284df-9629-4bc1-99e2-0b096dfa013b.png)

However, when I try to do a simple API request, it simply returns an error:
```
Execution failed with status 5000
Unknown host.
{
"headers":[...]
"httpMethod":"GET"
"url":"https://api.themoviedb.org/3/discover/movie?api_key=19f39f3c484954b02ac387996570be32"
}
```

![image](https://user-images.githubusercontent.com/22459531/175135915-068368f5-e870-431f-afbd-db13849736d6.png)

I'd tried to add the host by hand, as the error said unknow host, but no changes.
If you hit the api using the appsmith web page application (or even directly in the browser) it works:
![image](https://user-images.githubusercontent.com/22459531/175136107-d5601766-b461-46a6-a4e0-cc90577385e7.png)

Here is the docker-compose file I used:
```
version: "3"

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
    
  #   # Uncomment the lines below to enable auto-update
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  auto_update:
    image: containrrr/watchtower:latest-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Update check interval in seconds.
    command: --schedule "0 0 * ? * *" --label-enable --cleanup
    restart: unless-stopped
```

### Steps To Reproduce

1. Download the docker-compose.yml file from https://docs.appsmith.com/setup/docker
2. Run docker-compose up
3. Go to localhost:80 (or the port you defined)
4. Create new accont
5. Go to Queries/JS session > + > New Blank API:
![image](https://user-images.githubusercontent.com/22459531/175136687-ae5680db-613d-45d4-b3ad-6dc87b0e7eb3.png)
6. Hit run button:
![image](https://user-images.githubusercontent.com/22459531/175136893-1acd3839-4083-4cb7-b6d3-8580db077bbd.png)

Errors I got:
```
06:14:59 [Api2] Execution failed with status 5000
Unknown host.
{
"headers":[
]
"httpMethod":"GET"
"url":"https://api.themoviedb.org/3/discover/movie?api_key=19f39f3c484954b02ac387996570be32"
}



06:13:23 [Api2] Execution failed
{}
{
"headers":[
]
"body":{
}
"httpMethod":""
"url":""
}


06:03:46
[Api1] Execution failed with status 5000 
Unknown host.
{
"headers":[
0:{
"host":"api.themoviedb.org"
}
]
"httpMethod":"GET"
"url":"https://api.themoviedb.org/3/discover/movie?api_key=19f39f3c484954b02ac387996570be32"
}
```
![image](https://user-images.githubusercontent.com/22459531/175138134-a90359af-833f-446e-b1b1-52cd0385d2ba.png)

### Version

Self Hosted - Latest version
