### ISSUE TITLE
[Bug]: Certificate isn't generated when using Appsmith Helm Chart

### ISSUE THREAD

**Issue by jerowe** [appsmithorg/appsmith#17156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm trying to get the Appsmith helm chart up and running with SSL.

(This might be a me doing something stupid rather than a bug.)

Here's my values - 

```
## @section Ingress exposing parameters
## https://github.com/appsmithorg/appsmith/blob/release/deploy/helm/Setup-https.md
##  --set service.type=ClusterIP \
##  --set ingress.enabled=true \
##  --set ingress.tls=true \
##  --set ingress.certManager=true \
##  --set ingress.annotations."kubernetes\.io/ingress\.class"=nginx \
##  --set ingress.annotations."cert-manager\.io/cluster-issuer"=letsencrypt-prod \
##  --set ingress.hosts[0].host=DOMAIN \
##  --set ingress.certManagerTls[0].hosts[0]=DOMAIN \
##  --set ingress.certManagerTls[0].secretName=letsencrypt-prod
##  --set ingress.className=nginx

ingress:
  enabled: true
  tls: true
  className: nginx
  certManager: true
  certManagerTLS:
    - hosts:
        - ${aws_route53_record_name}.${aws_route53_domain_name}
      secretName: ${aws_route53_record_name}.${aws_route53_domain_name}-tls
  hostname: ${aws_route53_record_name}.${aws_route53_domain_name}
  hosts:
    - host: ${aws_route53_record_name}.${aws_route53_domain_name}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ${helm_release_name}-letsencrypt
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
service:
  type: ClusterIP
```

Relevant helm charts - 

```
# helm list -A
cert-manager            cert-manager    1               2022-09-26 11:39:16.924488 +0300 +03    deployed        cert-manager-v1.9.1     v1.9.1     
external-dns            default         1               2022-09-26 11:17:38.466928 +0300 +03    deployed        external-dns-1.11.0     0.12.2     
ingress-nginx           ingress-nginx   1               2022-09-26 14:54:08.781009 +0300 +03    deployed        ingress-nginx-4.2.5     1.3.1      
karpenter               karpenter       1               2022-09-19 17:36:57.481847 +0300 +03    deployed        karpenter-0.15.0        0.15.0    
```

I do have a cluster issuer:

```
#  kubectl get ClusterIssuer
NAME                          READY   AGE
appsmith-stable-letsencrypt   True    6h36m
```

The issue seems to be that the certificate isn't created. It is created for my other helm charts though so I don't think it's a cert-manager issue. For example, I have an Nginx app up for testing purposes.

```
 #kubectl get certificate
NAME                              READY   SECRET                            AGE
nginx-1.bioanalyzedev.io-tls      True    nginx-1.bioanalyzedev.io-tls      30h
```

<img width="533" alt="Screen Shot 2022-09-28 at 5 17 16 PM" src="https://user-images.githubusercontent.com/5555526/192803223-36d72640-813d-4f6a-9944-ca6ebf864dd5.png">

If you would like to contact me directly, I can send you a sample app. 

### Steps To Reproduce

```
 helm repo add appsmith http://helm.appsmith.com
helm repo update

# Using the yaml values from above:
helm upgrade --install appsmith-stable appsmith/appsmith -f ./values-from-above.yaml
```

### Version

Helm chart - appsmith-1.5.3
