### ISSUE TITLE
[Bug]: Upload of files larger than 5mb fails when changing port

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#17816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we change the ports `80:80` and `443:443` to `8080:80` and `443:8433` in the `docker-compose.yml`, uploading files larger than 5mb to a Postgres database fails, but files smaller than 5mb are successful.

### Steps To Reproduce

1.Start a self-hosted Appsmith with this docker-compose.yml
```yml
version: "3"

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
```
2. Add a Postgres data source to speed up the process, I attach a [docker-compose.yml](https://github.com/felix-appsmith/appsmith-quick-datasources#-postgresql)
3. Upload a file to the db less than 5mb and see how it uploads correctly.
4. Upload a file to the db of more than 5mb and see how it is not loaded, you can open the console to see part of the error.

### Version

Self hosted: Appsmith Community v1.8.5
