### ISSUE TITLE
[Bug]: Unable to start Appsmith after auto update (MongoDB cannot start)

### ISSUE THREAD

**Issue by WillemJann** [appsmithorg/appsmith#19542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since the update of Appsmith yesterday, my deployment does not work anymore. I get a 404 error when I try to reach Appsmith in the browser (https://appsmith.perfectxl.com). I think it is related to the upgrade of the MongoDB instance to v5.0.14.

This is my `docker-compose.yml` file:

```
version: "3"

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    expose:
      - "80"
      - "443"
      - "9001"
    volumes:
      - ./stacks:/appsmith-stacks
    networks:
      - traefik
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.appsmith.entrypoints=websecure"
      - "traefik.http.routers.appsmith.rule=Host(`appsmith.perfectxl.com`)"
      - "traefik.http.routers.appsmith.service=appsmith-service"
      - "traefik.http.services.appsmith-service.loadbalancer.server.port=80"
    restart: unless-stopped

  auto_update:
    image: containrrr/watchtower:latest-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Update check interval in seconds.
    command: --schedule "0 0 * ? * *" --label-enable --cleanup
    restart: unless-stopped

networks:
  traefik:
    external: true
```

### Steps To Reproduce

1. The status of docker is as follows:

```
root@docker:~/appsmith# docker-compose ps
         Name                       Command                   State                  Ports
----------------------------------------------------------------------------------------------------
appsmith                 /opt/appsmith/entrypoint.s ...   Up (unhealthy)   443/tcp, 80/tcp, 9001/tcp
appsmith_auto_update_1   /watchtower --schedule 0 0 ...   Up
```

2. The status of the supervisor is as follows:

```
root@docker:~/appsmith# docker-compose exec appsmith supervisorctl status
backend                          RUNNING   pid 1338, uptime 0:16:05
cron                             RUNNING   pid 1340, uptime 0:16:05
editor                           RUNNING   pid 1339, uptime 0:16:05
mongodb                          FATAL     Exited too quickly (process log may have details)
redis                            RUNNING   pid 1335, uptime 0:16:05
rts                              RUNNING   pid 1337, uptime 0:16:05
stdout                           RUNNING   pid 1334, uptime 0:16:05
```

3. This is the output when I try to start mongodb with the supervisor:

```
root@docker:~/appsmith# docker-compose exec appsmith supervisorctl start mongodb
mongodb: ERROR (spawn error)
```

4. This is what I get when I try to start mongodb manually: (based on [this template](https://github.com/appsmithorg/appsmith/blob/release/deploy/docker/templates/supervisord/mongodb.conf))

```
root@docker:~/appsmith# docker-compose exec appsmith bash
root@7d9941061565:/opt/appsmith# cd /appsmith-stacks/data/mongodb/
root@7d9941061565:/appsmith-stacks/data/mongodb# mongod --port 27017 --dbpath . --logpath /appsmith-stacks/logs/mongodb/db.log --replSet mr1 --keyFile /mongodb-key --bind_ip localhost
Illegal instruction (core dumped)
```

Do you have any suggestion to fix this deployment issue? What can I do to get Appsmith up and running?

If you need more information, let me know.

### Version

Self Hosted - latest Docker version (v1.9.1?)
