### ISSUE TITLE
[Bug]: SSL protocol error using caddy

### ISSUE THREAD

**Issue by accesstechnology-mike** [appsmithorg/appsmith#19958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

reference: #13783

using https://github.com/lucaslorentz/caddy-docker-proxy

appsmith can't start using SSL with caddy

_using http://app.domain.co.uk:8443 it runs fine, so the installation is ok_ 

### Steps To Reproduce

docker-compose.yml:

```
version: "3"

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "8043:80"
      - "44343:443"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
    # Uncomment the lines below to enable auto-update
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      caddy: app.domain.co.uk
      caddy.reverse_proxy: "{{upstreams 8043}}"
    networks:
      - caddy
    
  auto_update:
    image: containrrr/watchtower:latest-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Update check interval in seconds.
    command: --schedule "0 0 * ? * *" --label-enable --cleanup
    restart: unless-stopped
    depends_on:
      - appsmith
    environment:
     - WATCHTOWER_LIFECYCLE_HOOKS=true

networks:
  caddy:
    external: true
```

### Version

self-hosted latest
