### ISSUE TITLE
[Bug]: Error in the execution of SQL queries that use variables and subqueries in the FROM clause

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#19992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user tries to execute a query that uses variables and subqueries, this to make a mathematical calculation, the problem is that in Appsmith this query fails showing this error:`Parameter at position 0` is not set and grew it in a database manager like dbeaver, it runs successfully.

This query fails when using a `MariaDB` database.

![image](https://user-images.githubusercontent.com/114161539/214102005-e3508d8e-afe0-4530-9a9e-d6ca92ccdf3f.png)

![image](https://user-images.githubusercontent.com/114161539/214102281-c79e9c87-3551-4db3-bb30-6bed62919679.png)

### Steps To Reproduce

1. Create a MariaDB database can use this docker-compose.yml

  ```yml
version: '3'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql  
```

2. Create the table and insert the data for the query to work use this query

```sql
CREATE TABLE mytable (
  id INT,
  amt DECIMAL(10,2),
  qty INT
);

INSERT INTO mytable (id, amt, qty)
VALUES (1, 100, 2);
```

3. Now run this query in Appsmith and see the error:`Parameter at position 0`

 ```sql
 SELECT id, @amount := amt as amount, @quantity := qty as quantity, @amount * @quantity as charge FROM (
    SELECT id, amt, qty FROM mytable
) tmp;
 ```
 4. Run the same query in a database manager like `DBeaver`.
 

### Version

Self-hosted Appsmith Community v1.9.4
