### ISSUE TITLE
[Bug]: When using `appsmith` as a sub-chart, with `redis` and `mongo` enabled, the `appsmith` init-container command fails due to incorrect DNS

### ISSUE THREAD

**Issue by BadAsstronaut** [appsmithorg/appsmith#20047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I would like to add `appsmith` as a dependency on a `helm` chart. 

*Chart.yaml*
```yaml
apiVersion: v2
name: low-code-vinyl
description: A helm chart for a low-code vinyl (records) management platform
type: application
version: 0.1.0
appVersion: "1.16.0"
maintainers:
  - name: Mickey
    email: kyle.mickey@gmail.com
sources:
  - https://github.com/badasstronaut/low-code-vinyl
dependencies:
  - name: appsmith
    version: 2.0.0
    repository: https://helm.appsmith.com
  - name: postgresql
    version: 12.1.9
    repository: https://charts.bitnami.com/bitnami
```
The `appsmith` pod gets stuck on the init containers. 

Running `kubectl logs <appsmith_pod> -c redis-init-container` shows:
```plaintext
waiting for redis
Could not connect to Redis at low-code-vinyl-appsmith-redis-master.default.svc.cluster.local:6379: Name does not resolve
```
Debugging the chart, the `statefulset` generated for the `appsmith` chart has:

```yaml
initContainers:
      - command:
        - sh
        - -c
        - apk add redis; until redis-cli -h low-code-vinyl-appsmith-redis-master.default.svc.cluster.local
          ping; do echo waiting for redis; sleep 2; done
        image: alpine
        imagePullPolicy: Always
        name: redis-init-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
```

This is NOT the `APPSMITH_REDIS_URL` env provided in `values.yaml`:
```yaml
appsmith:
  redis:
    enabled: true
    auth:
      enabled: false
    replica:
      replicaCount: 1

  mongodb:
    enabled: true
    service:
      nameOverride: appsmith-mongodb
    auth:
      rootUser: root
      rootPassword: password
    replicaCount: 2
    architecture: "replicaset"
    replicaSetName: rs0

  image:
    repository: appsmith/appsmith-ce
    pullPolicy: IfNotPresent
    tag: latest

  applicationConfig:
    APPSMITH_OAUTH2_GOOGLE_CLIENT_ID: ""
    APPSMITH_OAUTH2_GOOGLE_CLIENT_SECRET: ""
    APPSMITH_OAUTH2_GITHUB_CLIENT_ID: ""
    APPSMITH_OAUTH2_GITHUB_CLIENT_SECRET: ""
    APPSMITH_FORM_LOGIN_DISABLED: ""
    APPSMITH_SIGNUP_DISABLED: ""
    APPSMITH_CLIENT_LOG_LEVEL: ""
    APPSMITH_GOOGLE_MAPS_API_KEY: ""
    APPSMITH_MAIL_ENABLED: ""
    APPSMITH_MAIL_HOST: ""
    APPSMITH_MAIL_PORT: ""
    APPSMITH_MAIL_USERNAME: ""
    APPSMITH_MAIL_PASSWORD: ""
    APPSMITH_MAIL_FROM: ""
    APPSMITH_REPLY_TO: ""
    APPSMITH_MAIL_SMTP_AUTH: ""
    APPSMITH_MAIL_SMTP_TLS_ENABLED: ""
    APPSMITH_DISABLE_TELEMETRY: ""
    APPSMITH_RECAPTCHA_SITE_KEY: ""
    APPSMITH_RECAPTCHA_SECRET_KEY: ""
    APPSMITH_RECAPTCHA_ENABLED: ""
    APPSMITH_MONGODB_URI: appsmith-mongodb.default.svc.cluster.local
    APPSMITH_REDIS_URL: low-code-vinyl-redis-master.default.svc.cluster.local
    APPSMITH_ENCRYPTION_PASSWORD: ""
    APPSMITH_ENCRYPTION_SALT: ""
    APPSMITH_CUSTOM_DOMAIN: ""
    APPSMITH_DISABLE_IFRAME_WIDGET_SANDBOX: "false"
```

### Steps To Reproduce

1. Create a Helm chart and add appsmith as a dependency
2. Add the appsmith values to the `values.yaml` 
3. Try to install the helm package; e.g. `helm install test-appsmith .`
4. Check the DNS generated for the `redis-master` pod
5. Compare to the DNS generated by the init-containers template

Recommendation: The appsmith statefulset template should reference the `APPSMITH_REDIS_URL` from `values.yaml`.

### Version

Self-hosted K8s
