### ISSUE TITLE
[Feature]: Self hosting Google fonts

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#20365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A user has requested to load the google fonts from different CDN to optimize the loading speed.

**Front link**: https://app.frontapp.com/inboxes/teams/folders/15896140/unassigned/70477439692
**Slack Thread**: https://theappsmith.slack.com/archives/C0341RERY4R/p1675403397627839

### Why should this be worked on?

By self-hosting the google fonts we can optimize the loading speed.

**Comment by somangshu** [comment]
@SatishGandham I remember this was being discussed, where we said loading static resources from CDN will help resolve network latency we see today to some extent. Is this a similar issue?

cc @ichik @jsartisan this might be relevant to WDS

**Comment by ichik** [comment]
Copying over relevant info from the linked issue.

Some links explaining why self-hosting (and preloading, sub-setting binaries, and using variable fonts wherever possible + a bunch other tricks) is preferable to using Google Fonts:
https://evilmartians.com/chronicles/the-joy-of-variable-fonts-getting-started-on-the-frontend
https://pimpmytype.com/variable-font-fallback/
https://wpspeedmatters.com/self-host-google-fonts/
https://css-tricks.com/dont-just-copy-the-font-face-out-of-google-fonts-urls/

Nice CLI tool for sub-setting binaries: https://github.com/zachleat/glyphhanger

Sample code for self-hosting:

```CSS
/* Variable fonts */
/* English */
@font-face {
    font-family: 'FooV';
    font-weight: 400 700; /* Whatever's actually in the font file, same for font-style */
    font-display: swap; /* https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display#values */
    font-style: oblique 0deg 10deg;
    src: url('https://foo.bar/fonts/en.var.woff2') format('woff2');
    unicode-range: U+0020-007F, U+AB, U+BB;
}
/* Cyrillic */
@font-face {
    font-family: 'FooV';
    font-weight: 400 700;
    font-display: swap;
    font-style: oblique 0deg 10deg;
    src: url('https://foo.bar/fonts/cyr.var.woff2') format('woff2');
    unicode-range: U+401, U+404, U+406, U+407, U+410-44F, U+451, U+454, U+456, U+457, U+490, U+491;
}

...

/* Duplicating this all for all needed Unicode ranges */

/* Non-variable fonts */
/* English */
@font-face {
    font-family: 'Foo';
    font-style: normal;
    font-weight: 400;
    font-display: swap;
    src: url('https://foo.bar/fonts/en.regular.woff2') format('woff2');
    unicode-range: U+0020-007F, U+AB, U+BB;
}
@font-face {
    font-family: 'Foo';
    font-style: normal;
    font-weight: 500;
    font-display: swap;
    src: url('https://foo.bar/fonts/cyr.regular.woff2') format('woff2');
    unicode-range: U+0020-007F, U+AB, U+BB;
}

...

/* Duplicating for all necessary weights and styles and Unicode ranges*/

/* Declaring a fallback */

@font-face {
    font-family: 'Foo-Fallback';
    size-adjust: 109.71%;
    src: local('Arial'); /* Arial is the most available fallback for sans-serifs. ref: http://fontfamily.io */
}

/* Applying variable when supported */
* {
    font-family: 'Foo', 'Foo-Fallback', sans-serif;
}

@supports (font-variation-settings: normal) {
    * {
        font-family: 'FooV', 'Foo-Fallback', sans-serif;
    }
}
```

Links for defining and previewing Unicode ranges:
- https://character-table.netlify.app 
- https://www.unicodepedia.com/groups/ 
- https://www.zachleat.com/unicode-range-interchange/

Preloading directives for `<head>`:

```html
<!-- if we're loading from some other place -->
<link rel="preconnect" href="https://foo.com" crossorigin>
<!-- Prefetching the binary before the stylesheet -->
<link rel="preload" href="https://foo.com/bar.woff2" as="font" type="font/woff2" crossorigin>
<!-- Typography-related CSS should be requested after -->
<link rel=stylesheet" href="typography.css">
```
