### ISSUE TITLE
Get rid of font FOUT

### ISSUE THREAD

**Issue by KelvinOm** [appsmithorg/appsmith#21427]
It is necessary to find and propose a solution to avoid FOUT(Flash of Unstyled Text) for apps and editor.

Possible solutions: 
1. Self-hosting of the fonts
2. Google Fonts Preloading

**Comment by ichik** [comment]
Some relevant links explaining why self-hosting (and preloading, sub-setting binaries, and using variable fonts wherever possible + a bunch other tricks) is preferable to using Google Fonts:
https://evilmartians.com/chronicles/the-joy-of-variable-fonts-getting-started-on-the-frontend
https://pimpmytype.com/variable-font-fallback/
https://wpspeedmatters.com/self-host-google-fonts/
https://css-tricks.com/dont-just-copy-the-font-face-out-of-google-fonts-urls/

**Comment by ichik** [comment]
Nice CLI tool for sub-setting binaries: https://github.com/zachleat/glyphhanger

**Comment by ichik** [comment]
Sample code for self-hosting:

```CSS
/* Variable fonts */
/* English */
@font-face {
    font-family: 'FooV';
    font-weight: 400 700; /* Whatever's actually in the font file, same for font-style */
    font-display: swap; /* https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display#values */
    font-style: oblique 0deg 10deg;
    src: url('https://foo.bar/fonts/en.var.woff2') format('woff2');
    unicode-range: U+0020-007F, U+AB, U+BB;
}
/* Cyrillic */
@font-face {
    font-family: 'FooV';
    font-weight: 400 700;
    font-display: swap;
    font-style: oblique 0deg 10deg;
    src: url('https://foo.bar/fonts/cyr.var.woff2') format('woff2');
    unicode-range: U+401, U+404, U+406, U+407, U+410-44F, U+451, U+454, U+456, U+457, U+490, U+491;
}

...

/* Duplicating this all for all needed Unicode ranges */

/* Non-variable fonts */
/* English */
@font-face {
    font-family: 'Foo';
    font-style: normal;
    font-weight: 400;
    font-display: swap;
    src: url('https://foo.bar/fonts/en.regular.woff2') format('woff2');
    unicode-range: U+0020-007F, U+AB, U+BB;
}
@font-face {
    font-family: 'Foo';
    font-style: normal;
    font-weight: 500;
    font-display: swap;
    src: url('https://foo.bar/fonts/cyr.regular.woff2') format('woff2');
    unicode-range: U+0020-007F, U+AB, U+BB;
}

...

/* Duplicating for all necessary weights and styles and Unicode ranges*/

/* Declaring a fallback */

@font-face {
    font-family: 'Foo-Fallback';
    size-adjust: 109.71%;
    src: local('Arial'); /* Arial is the most available fallback for sans-serifs. ref: http://fontfamily.io */
}

/* Applying variable when supported */
* {
    font-family: 'Foo', 'Foo-Fallback', sans-serif;
}

@supports (font-variation-settings: normal) {
    * {
        font-family: 'FooV', 'Foo-Fallback', sans-serif;
    }
}
```

Links for defining and previewing Unicode ranges:
- https://character-table.netlify.app 
- https://www.unicodepedia.com/groups/ 
- https://www.zachleat.com/unicode-range-interchange/
