### ISSUE TITLE
[Bug]: OAuth 2.0 token is NOT refreshed

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#21769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are not authenticating a data source in this case with Zoho. Zoho provides a token that expires approximately an hour after it is obtained. Once the token expires, Appsmith does not automatically refresh this token, which causes the API to fail.

### Steps To Reproduce

1.  Enter the [[Zoho development console](https://api-console.zoho.com/add)](https://api-console.zoho.com/add).
2. Create a new client and use the client called 'Server-based Applications'.
3. Get your Homepage URL in Appsmith.
Configure the application as follows:
```yml
Client Name: <<Appname>>
Homepage URL: <<YourAppsmithApplicationURL>>
Authorized Redirect URIs: https://app.appsmith.com/api/v1/datasources/authorize
```

4. Press the `CREATE` button.
5. After creating your application, you will obtain your Client ID and Client Secret credentials on a dashboard like this.
6. Add a new data source of `Authenticated API` type
7. Data source configuration
8. 
```YAML
URL: https://expense.zoho.com/
Authentication Type: OAuth 2.0
Grant Type: Authorization Code
Add Access Token To: Request Header
Header Prefix: Bearer
Access Token URL: https://accounts.zoho.com/oauth/v2/token
Client ID: <<YourClientID>>
Client Secret: <<YourClientSecret>>
Scope(s): ZohoExpense.fullaccess.ALL
Client Authentication: Send as Basic Auth header
Authorization URL: https://accounts.zoho.com/oauth/v2/auth
```
9. Press the `Save and Authorize` button.
10. Verify that everything is working by running this query: `api/v1/organizations` from this data source using this endpoint. You should receive this output if everything went well.

After an hour and a half the token will expire and appsmith will not refresh it

### Public Sample App

https://app.appsmith.com/app/cnv-y3rxhu4/page1-641a223433970d1990c88202

### Environment

Production

### Issue video log

https://www.loom.com/share/22988ee151e7486396caf325a15aa67e

### Version

Appsmith v1.9.12-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_9gklo)
