### ISSUE TITLE
[Bug]: It is not possible to connect to MySQL and MSSQL using the IP address in the self-hosted version.

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#22740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Previously in Appsmith self-hosted, I was able to connect to my data sources using my IP address. Currently, this is not working, and it doesn't allow me to connect using the IP/instancename either. However, if I expose the port of my data source with ngrok, then I can connect perfectly fine.

### Steps To Reproduce

1. Create a new data source using docker, you can use this docker-compose.
```yml
version: '3.7'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "yopassword123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - mi-red
networks:
  mi-red:

```
2. Use the command `ifconfig` to see your IP address.

3. Connect from Appsmith to your data source using your IP address, and you will see that it fails.

4. Make the same connection but using Dbeaver and you will see that it succeeds.

5. Expose the port of the data source with ngrok and try to make the connection with Appsmith, and you will see that it works successfully.

Here is my configuration:

IP/instancename:port

IP:port

In both cases, it fails, but if I expose it with ngrok, both cases work. I am attaching the docker-compose file for MsSql, but it also fails with MySQL.

### Environment

Production

### Version

Self-Hosted 1.9.16,   1.9.15,  1.9.4
