### ISSUE TITLE
[Bug]: External Mongo fails ReplicaSet check with readWrite Permission

### ISSUE THREAD

**Issue by sum35h** [appsmithorg/appsmith#23117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A User has been able to configure replica set, but they needed to assign `readWriteAnyDatabase` which is not good for PoLP. 
The replica set check failed with `readWrite` permission.

### Steps To Reproduce

1. Provision MongoDB cluster in Atlas
2. Create a user with readWrite role only
3. Use the above credentials on an Appsmith Instance
4. Observe the ReplicaSet check details in the logs

### Environment

Production

### Version

1.9.17

**Comment by organicnz** [comment]
Encountering the same issue:

```
***************************************************************************************
*      MongoDB Replica Set is not enabled                                             *
*      Please ensure the credentials provided for MongoDB, has 'readWrite' role.      *
***************************************************************************************
```

**Comment by antonchernyaev-kit-ar** [comment]
have same....

```
applicationConfig: {}
autoupdate:
  enabled: false
  scheduler: 3 * * * *
global:
  namespaceOverride: ""
  storageClass: efs--persist--1001-777
ingress:
  certManager: false
  certManagerTls: []
  enabled: false
  secrets: []
  tls: false
mongodb:
  architecture: standalone
  auth:
    rootPassword: xxxxxxxxxxxxxxx
    rootUser: root
  containerSecurityContext:
    enabled: false
  directoryPerDB: true
  enabled: true
  initContainers:
  - args:
    - -xec
    - |
      id ||true
      (mount |grep nfs) ||true
      (mount |grep efs) ||true
      ls -la / ||true
      ls -la /i-mount ||true
      find /i-mount || true
    command:
    - /bin/bash
    image: public.ecr.aws/bitnami/bitnami-shell:latest
    imagePullPolicy: IfNotPresent
    name: volume-premissions-tmp
    securityContext:
      runAsUser: 0
    volumeMounts:
    - mountPath: /i-mount
      name: datadir
  podSecurityContext:
    enabled: false
  replicaCount: 1
  volumePermissions:
    enabled: true
    securityContext:
      runAsUser: auto
persistence:
  enabled: true
  size: 10Gi
postgresql:
  enabled: false
redis:
  auth:
    enabled: true
    password: xxxxxxxxxxxxxxxxxxxxxxxxx
  enabled: "true"
  master: null
  replica:
    replicaCount: 1
secretName: appsmith-secret-1--240326a
service:
  type: ClusterIP
strategyType: RollingUpdate
```
