### ISSUE TITLE
[Bug]: Issues in starting appsmith with proxy

### ISSUE THREAD

**Issue by pratapaprasanna** [appsmithorg/appsmith#24013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

```
version: "3"

services:
  appsmith:
    image: appsmith/appsmith-ee:nightly
    container_name: appsmith
    ports:
      - "80:80"
      - "443:443"
      - "9991:9991"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
    environment:
      HTTPS_PROXY: "1.2.3.4"
      HTTP_PROXY: "1.2.3.4"
```

### Steps To Reproduce

docker-compose up 
and the logs are as follows

```
 % Total  % Received % Xferd Average Speed Time  Time  Time Current
                 Dload Upload Total Spent  Left Speed
100 187 100  21 100 166  23  183 --:--:-- --:--:-- --:--:-- 206
{
 "success": true
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
} % Total  % Received % Xferd Average Speed Time  Time  Time Current
                 Dload Upload Total Spent  Left Speed
100 187 100  21 100 166  22  179 --:--:-- --:--:-- --:--:-- 201
{
 "success": true
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
```

### Environment

Production

### Version

v1.9.20.4
