### ISSUE TITLE
[Feature]: Caddy support on Docker compose

### ISSUE THREAD

**Issue by organicnz** [appsmithorg/appsmith#24573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hey folks,

Thanks so much for your kind help and the offer to file a feature request for the Caddy support on Discord :) 

Here's my use case :)

```
version: "3.8"

services:
  mongo1:
    image: mongo
    container_name: mongo1
    command: ["--replSet", "rs0", "--dbpath", "/data/db", "--bind_ip_all"]
    volumes:
      - ./mongo/data1/db:/data/db
      - ./mongo/data1/configdb:/data/configdb
    restart: unless-stopped
    networks:
      - no-zero-trust-cloudflared
      
  mongo-config:
    image: mongo
    networks:
      - no-zero-trust-cloudflared
      - zero-trust-cloudflared
    depends_on:
      - mongo1
        #      - mongo2
        #      - mongo3
    volumes:
      - ./scripts:/scripts
    restart: unless-stopped
    entrypoint: ['/scripts/mongo-setup.sh']

  appsmith:
    image: index.docker.io/appsmith/appsmith-ee
    container_name: appsmith
    ports:
      - "8080:80"
        #- "443:443"
        #- "80:80"
    volumes:
      - ./stacks:/appsmith-stacks
    environment:
      #      - DATABASE_URL=mongodb://mongodb:27017/appsmith
      - SERVER_PORT=8080
        #      - APPSMITH_CUSTOM_DOMAIN=appsmith.foodshare.club
    restart: unless-stopped
    # Uncomment the lines below to enable auto-update
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    mem_limit: "1g"
    mem_reservation: "1g"
    cpus: 1
    cpuset: "0"
    networks:
      - no-zero-trust-cloudflared
    depends_on:
      - mongo1

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${DATA_FOLDER}/caddy_data:/data
      - ${DATA_FOLDER}/caddy_config:/config
      - ${DATA_FOLDER}/caddy_config/Caddyfile:/etc/caddy/Caddyfile
    mem_limit: "1g"
    mem_reservation: "1g"
    cpus: 1
    cpuset: "0"
    networks:
     - no-zero-trust-cloudflared
     - web

networks:
  web:
    external: true
    name: web
  no-zero-trust-cloudflared:
    external: false
    driver: bridge
    name: no-zero-trust-cloudflared

volumes:
  caddy_data:
    external: true
  caddy_config:
```

$ cat caddy_config/Caddyfile
```
{
    # Global options block. Entirely optional, https is on by default
    # Optional email key for lets encrypt
    email tamerlanium@gmail.com
    # Optional staging lets encrypt for testing. Comment out for production.
    # acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
}

appsmith.foodshare.club {
    encode zstd gzip
    reverse_proxy appsmith:8080 {
      flush_interval -1
    }
    header {
        # enable HSTS
        Strict-Transport-Security max-age=31536000;
        # disable clients from sniffing the media type
        X-Content-Type-Options nosniff
        # clickjacking protection
        X-Frame-Options DENY
        # keep referrer data off of HTTP connections
        Referrer-Policy no-referrer-when-downgrade
        # Content-Security-Policy: default-src 'self'
    }
}

www.appsmith.foodshare.club {
    redir https://appsmith.foodshare.club{uri}
}
```

$ cat .env
```
# Path where you created folders earlier.
# Change this if you didn't create them in the repo checked out in the root directory.
DATA_FOLDER=/home/organic/dev/appsmith

# The email address to use for the SSL certificate creation
SSL_EMAIL=tamerlanium@gmail.com
```

$ cat scripts/mongo-setup.sh
```
#!/bin/bash
sleep 15

mongodb1=$(getent hosts mongo1 | awk '{ print $1 }')
#mongodb2=$(getent hosts mongo2 | awk '{ print $1 }')
#mongodb3=$(getent hosts mongo3 | awk '{ print $1 }')

port=${PORT:-27017}

echo "Waiting for startup.."
until curl http://${mongodb1}:27017/serverStatus\?text\=1 2>&1| grep uptime | head -1; do
  printf '.'
  sleep 1
done


echo "Started.."
echo "setup.sh; time now: $(date +"%T")"


mongo --host ${mongodb1}:${port} <<EOF
   var cfg = {
        "_id": "rs0",
        "members": [
            {
                "_id": 0,
                "host": "${mongodb1}:${port}",
                "priority":1
            }
#            {
#                "_id": 1,
#                "host": "${mongodb2}:${port}",
#                "priority":0.5
#            },
#            {
#                "_id": 2,
#                "host": "${mongodb3}:${port}",
#                "priority":0.5
#            }
        ],settings: {chainingAllowed: true}
    };
    rs.initiate(cfg, { force: true });
    rs.reconfig(cfg, { force: true });
    rs.status();
EOF
```

### Why should this be worked on?

Caddy is a web server that is known for its simplicity and ease of use, especially when it comes to handling SSL certificate issuance for domains. Caddy has built-in support for automatic SSL/TLS certificate provisioning and renewal using Let's Encrypt, a free and open certificate authority.
