### ISSUE TITLE
[Bug]: Auto-Update Not Working

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#27363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A [user](https://app.frontapp.com/open/cnv_13nc3558?key=nCx4JWHmeKAbqrx0JQ5mIUZr3m5p29qJ) reported having problems with the Appsmith auto-updates functionality that is enabled in the `docker-compose` file. They mentioned that they get a message saying “Session done” but their instance is not updated (“Updated=0"). After reviewing the logs, they got advised to change the refresh check frequency to 30 seconds and after checking the Docker version, the user confirmed that the issue persists and their instance is not being refreshed.

I did some tests deploying a self-hosted instance with version 1.9.33 and configuring auto-updates every 30 seconds. As a result of this, I was able to replicate the user's error, as I got the same message and verified that, although an update was apparently being made, ultimately my instance was still on version 1.9.33.

![image](https://github.com/appsmithorg/appsmith/assets/114161539/54d30229-af88-4727-aac9-64e333855993)
![image](https://github.com/appsmithorg/appsmith/assets/114161539/4de675d9-ae6d-4121-93af-216009fb37d6)

### Steps To Reproduce

1. You can use this `docker-compose.yaml` file or the one you have. Modify the line `command: --schedule "0,30 * * ? * *" --label-enable --cleanup` if you want to check for updates with another periodicity.

```
version: "3"

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce:v1.9.33
    container_name: appsmith
    ports:
      - "8080:80"
      - "8443:443"
      - "9801:9001"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
    # Uncomment the lines below to enable auto-update
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  auto_update:
    image: containrrr/watchtower:latest-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Update check interval in seconds.
    command: --schedule "0,30 * * ? * *" --label-enable --cleanup
    restart: unless-stopped
    depends_on:
      - appsmith
    environment:
      - WATCHTOWER_LIFECYCLE_HOOKS=true
```

2. Let the instance running for some time (maybe some days) and notice that Appsmith was not updated by accessing it. 

### Environment

Production

### Version

Self-Hosted v1.9.33
