### ISSUE TITLE
[Bug]: Appsmith container not running on "docker-compose up -d"

### ISSUE THREAD

**Issue by ashutosh1211** [appsmithorg/appsmith#28209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Dont know but suddenly the appsmith instand is down and we are not able to use our instance.
When I did docker-compose up -d it is saying 
```
appsmith_auto_update_1 is up-to-date
Starting appsmith ... done

```

But there is no container running on checking docker command, only auto update container is running. 

`docker ps`

### Steps To Reproduce

No steps as we didnt made any changes.

### Environment

Production

### Version

Self Hosted

**Comment by sharat87** [comment]
Hey @ashutosh1211, sorry you're having trouble here and thanks for reaching out.

Can you share the following to help us troubleshoot please?

1. Output of `docker ps -a`
2. Output of `docker image inspect appsmith/appsmith-ce -f '{{.RepoTags}}'`
3. the `docker-compose.yml` file you're using here

Thank you very much for your patience and understanding here. 🙏

**Comment by ashutosh1211** [comment]
Yes sure, Please find below information


1. Output of docker ps -a

![image](https://github.com/appsmithorg/appsmith/assets/4639147/9ad17945-b9b6-4ecf-9703-1bb2d3de9af2)

2. Output of docker image inspect appsmith/appsmith-ce -f '{{.RepoTags}}'

![image](https://github.com/appsmithorg/appsmith/assets/4639147/964072c1-f60f-4ed2-ac2d-c1d931382187)

3. the docker-compose.yml file you're using here
```
version: "3"

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "80:80"
      - "443:443"
      - "9001:9001"
    volumes:
      - ./stacks:/appsmith-stacks
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  auto_update:
    image: containrrr/watchtower:latest-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Update check interval in seconds.
    command: --interval 300 --label-enable --cleanup
```
