### ISSUE TITLE
[Bug]: Helm chart does not build correctly 

### ISSUE THREAD

**Issue by vgiannone3** [appsmithorg/appsmith#28242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When creating building the helm chart, the appsmith container in the appsmith StatefulSet, has a duplicate SecurityContext that is created. It produces this error when trying the kustomize the resources to kubernetes:
error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 84: mapping key "securityContext" already defined at line 40

When reviewing the chart template for the StatefulSet, there appears to be the following SecurityContext hardcoded:
          securityContext:
            allowPrivilegeEscalation: false
Along with the templated SecurityContext:
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

### Steps To Reproduce

1. helm pull appsmith/appsmith --untar --namespace appsmith
2. helm template appsmith --include-crds --create-namespace appsmith > chart.yaml
3. Review the appsmith container in the appsmith StatefulSet and you will see the duplicate SecurityContext

### Environment

Production

### Version

Self Hosted v1.9.41

**Comment by sharat87** [comment]
Thank you for reporting this @vgiannone3. We've picked it up and working to fix this now. Thanks.

**Comment by dirathea** [comment]
Hello @pratapaprasanna I try to pull appsmith helm chart of 2.0.7, and found it still broken with the default values.

```
❯ helm template ./appsmith-2.0.7.tgz
Error: YAML parse error on appsmith/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 39: did not find expected key

Use --debug flag to render out invalid YAML
```

I found that it has incorrect rendering on the security context again as if you provide the default security context, it will render as follows

```yaml
      containers:
        - name: appsmith
          securityContext:
            allowPrivilegeEscalation: false
            {}
          image: "index.docker.io/appsmith/appsmith-ce:latest"
          imagePullPolicy: IfNotPresent
```

My suggestion is to put the default securityContext as the default helm chart values.
