### ISSUE TITLE
[Bug]: applicationConfig settings not being picked up (ex: mail)

### ISSUE THREAD

**Issue by joaocc** [appsmithorg/appsmith#35574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are trying to deploy appsmith-ee chart v3.3.0 and we defined .applicationConfig to set email related settings:

```
  APPSMITH_MAIL_ENABLED: "true"
  APPSMITH_MAIL_SMTP_AUTH: "true"
  APPSMITH_MAIL_SMTP_TLS_ENABLED: "true"
  APPSMITH_MAIL_HOST: smtp.sendgrid.net
  APPSMITH_MAIL_PORT: "587"
  APPSMITH_MAIL_USERNAME: apikey
  APPSMITH_MAIL_PASSWORD: xxxxx
  APPSMITH_MAIL_FROM: no-reply@something.domain.here
  APPSMITH_REPLY_TO: no-reply-to@something.domain.here
```

However, in https://myserver/settings/email the corresponding fields are empty.

This also happens if the values are passed as env-variables using de .secret field.

In both cases, a shell in the pod shows the variables to the correct values.

### Steps To Reproduce

deploy using helm chart values.yaml file containing
```
applicationConfig:
(...)
  APPSMITH_MAIL_ENABLED: "true"
  APPSMITH_MAIL_SMTP_AUTH: "true"
  APPSMITH_MAIL_SMTP_TLS_ENABLED: "true"
  APPSMITH_MAIL_HOST: smtp.sendgrid.net
  APPSMITH_MAIL_PORT: "587"
  APPSMITH_MAIL_USERNAME: apikey
  APPSMITH_MAIL_PASSWORD: xxxxx
  APPSMITH_MAIL_FROM: no-reply@something.domain.here
  APPSMITH_REPLY_TO: no-reply-to@something.domain.here
(...)
```

Login for the first time, go the email configuration page

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

self-hosted, appsmith-ee:v1.32 (chart 3.3.0)
