### ISSUE TITLE
[Bug]: illegal Instruction : /opt/appsmith/entrypoint.sh: line 241:   102 Illegal instruction     mongod --fork --port 27017 --dbpath "$MONGO_DB_PATH" --logpath "$MONGO_LOG_PATH"

### ISSUE THREAD

**Issue by nodecentral** [appsmithorg/appsmith#37307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I’m afraid there’s not much more I can add, Appsmith will not load, seems to try but just fail all the time.  Log extract is below.

````
}{   "commitSha": "2d92ac2c88fe26566155f2ded22eebb826b97de3",   "commitUrl": "[https://github.com/appsmithorg/appsmith-ee/commit/2d92ac2c88fe26566155f2ded22eebb826b97de3",](https://github.com/appsmithorg/appsmith-ee/commit/2d92ac2c88fe26566155f2ded22eebb826b97de3%22,)   "githubRef": "refs/tags/v1.48",   "githubRunUrl": "[https://github.com/appsmithorg/appsmith-ee/actions/runs/11740064412/attempts/1",](https://github.com/appsmithorg/appsmith-ee/actions/runs/11740064412/attempts/1%22,)   "version": "v1.48",   "imageBuiltAt": "2024-11-08T10:16:51+00:00",   "isCI": true } Successfully started Caddy (pid=74) - Caddy is running in the background
2024-11-09T20:18:57.993Z Checking environment configuration
2024-11-09T20:18:58.011Z Configuring database connection URL
2024-11-09T20:18:58.020Z Checking APPSMITH_DB_URL
2024-11-09T20:18:58.024Z Detected local DB
2024-11-09T20:18:58.032Z Initializing MongoDB
2024-11-09T20:18:58.038Z Initializing local database
'/appsmith-stacks/data/mongodb/key' -> '/tmp/appsmith/mongodb-key'
level=
info
ts=
1731183538.1305704
logger=
tls
msg=
storage cleaning happened too recently; skipping for now
storage=
FileStorage:/appsmith-stacks/data/caddy
instance=
207b4ca0-492b-4358-aedd-5b6fed055558
try_again=
1731269938.1305661
try_again_in=
86399.999999055
level=
info
ts=
1731183538.1307247
logger=
tls
msg=
finished cleaning storage units
2024-11-09T20:18:58.136Z Checking initialized database
2024-11-09T20:18:58.144Z Initializing Replica Set for local database
/opt/appsmith/entrypoint.sh: line 241:   109 Illegal instruction     mongod --fork --port 27017 --dbpath "$MONGO_DB_PATH" --logpath "$MONGO_LOG_PATH"
2024-11-09T20:20:01.436Z Running as: uid=0(root) gid=0(root) groups=0(root)
2024-11-09T20:20:01.970Z Initialize .env file
2024-11-09T20:20:01.974Z Load environment configuration
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
{
  "success": true

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   172  100    21  100   151     29    211 --:--:-- --:--:-- --:--:--   241
level=
info
ts=
1731183604.7251027
msg=
using config from file
file=
/tmp/appsmith/Caddyfile
level=
info
ts=
1731183604.73213
msg=
adapted config to JSON
adapter=
caddyfile
level=
info
ts=
1731183604.7350163
logger=
admin
msg=
admin endpoint started
address=
0.0.0.0:2019
enforce_origin=
false
origins=
["//0.0.0.0:2019"]
level=
warn
ts=
1731183604.7350657
logger=
admin
msg=
admin endpoint on open interface; host checking disabled
address=
0.0.0.0:2019
level=
info
ts=
1731183604.742299
logger=
tls.cache.maintenance
msg=
started background certificate maintenance
cache=
0xc0006ea300
level=
warn
ts=
1731183604.7512512
logger=
http.auto_https
msg=
server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server
server_name=
srv0
http_port=
80
level=
debug
ts=
1731183604.7529936
logger=
http.auto_https
msg=
adjusted config
tls.automation.policies=
[{}]
http.servers.srv0.automatic_https.disable=
true
http.servers.srv0.errors.routes=
[{"handle":[{"handler":"headers","response":{"deferred":true,"delete":["Server","Cache-Control"]}},{"body":"{http.error.status_code} {http.error.status_text}","handler":"static_response","status_code":"{http.error.status_code}"}]}]
http.servers.srv0.listen=
[":80"]
http.servers.srv0.logs.default_logger_name=
log0
http.servers.srv0.routes=
[{"handle":[{"handler":"vars","root":"/opt/appsmith/editor"}]},{"handle":[{"handler":"vars","log_skip":true}]},{"handle":[{"handler":"vars","log_skip":true}]},{"handle":[{"handler":"headers","response":{"set":{"X-Request-Id":["{http.request.header.X-Request-Id}"]}}}]},{"handle":[{"handler":"headers","response":{"set":{"X-Request-Id":["invalid_request_id"]}}}]},{"handle":[{"handler":"headers","response":{"set":{"Cache-Control":["public, max-age=31536000, immutable"]}}}]},{"handle":[{"handler":"headers","response":{"deferred":true,"delete":["Server"],"set":{"Content-Security-Policy":["frame-ancestors 'self' *"],"X-Appsmith-Request-Id":["{http.request.uuid}"],"X-Content-Type-Options":["nosniff"]}}},{"handler":"request_body","max_size":150000000}]},{"handle":[{"handler":"static_response","headers":{"Location":["/supervisor/"]},"status_code":302}]},{"handle":[{"handler":"static_response","headers":{"Location":["/auth/"]},"status_code":302}]},{"handle":[{"handler":"rate_limit","rate_limits":{"dynamic_zone":{"key":"{http.request.client_ip}","max_events":100,"window":1000000000}}}]},{"handle":[{"handler":"headers","request":{"set":{"X-Request-Id":["invalid_request_id"]}}}]},{"handle":[{"handler":"headers","request":{"delete":["X-Appsmith-Request-Id"]}}]},{"group":"group10","handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"tracing","span":"caddy_static_file"},{"canonical_uris":false,"handler":"file_server","hide":["/tmp/appsmith/Caddyfile"],"precompressed":{"br":{},"gzip":{}},"precompressed_order":["br","gzip"]}]}]}]},{"group":"group10","handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"tracing","span":"caddy_static_file_error"},{"handler":"error","status_code":404}]}]}]},{"group":"group10","handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"tracing","span":"caddy_api"},{"handler":"vars","root":"/opt/appsmith"}]},{"group":"group3","handle":[{"handler":"rewrite","uri":"/info.json"}]},{"handle":[{"canonical_uris":false,"handler":"file_server","hide":["/tmp/appsmith/Caddyfile"],"precompressed":{"br":{},"gzip":{}},"precompressed_order":["br","gzip"]}]}]}]},{"group":"group10","handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"tracing","span":"caddy_api"},{"handler":"reverse_proxy","headers":{"request":{"delete":["Forwarded"],"set":{"X-Appsmith-Request-Id":["{http.request.uuid}"]}}},"upstreams":[{"dial":"127.0.0.1:8080"}]}]}]}]},{"group":"group10","handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"rewrite","strip_path_prefix":"/supervisor"}]},{"handle":[{"handler":"reverse_proxy","headers":{"request":{"delete":["Forwarded"],"set":{"X-Appsmith-Request-Id":["{http.request.uuid}"]}}},"upstreams":[{"dial":"127.0.0.1:9001"}]}]}]}]},{"group":"group10","handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"tracing","span":"caddy_api"},{"handler":"reverse_proxy","headers":{"request":{"delete":["Forwarded"],"set":{"X-Appsmith-Request-Id":["{http.request.uuid}"]}}},"upstreams":[{"dial":"127.0.0.1:8081"}]}]}]}]},{"group":"group10","handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"tracing","span":"caddy_api"},{"handler":"reverse_proxy","headers":{"request":{"delete":["Forwarded"],"set":{"X-Appsmith-Request-Id":["{http.request.uuid}"]}}},"upstreams":[{"dial":"127.0.0.1:8886"}]}]}]}]},{"group":"group10","handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"tracing","span":"caddy_api"},{"handler":"reverse_proxy","headers":{"request":{"delete":["Forwarded"],"set":{"X-Appsmith-Request-Id":["{http.request.uuid}"]}}},"upstreams":[{"dial":"127.0.0.1:8091"}]}]}]}]},{"group":"group10","handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"tracing","span":"caddy_static_file"},{"handler":"vars","root":"/tmp/appsmith/www"}]},{"handle":[{"handler":"rewrite","uri":"{http.matchers.file.relative}"}],"match":[{"file":{"try_files":["/loading.html","/index.html"]}}]},{"handle":[{"canonical_uris":false,"handler":"file_server","hide":["/tmp/appsmith/Caddyfile"],"precompressed":{"br":{},"gzip":{}},"precompressed_order":["br","gzip"]}]}]}]}]
http.servers.srv0.trusted_proxies.ranges=
["0.0.0.0/0"]
http.servers.srv0.trusted_proxies.source=
static
level=
debug
ts=
1731183604.7979689
logger=
http
msg=
starting server loop
address=
[::]:80
tls=
false
http3=
false
level=
info
ts=
1731183604.7980464
logger=
http.log
msg=
server running
name=
srv0
protocols=
["h1","h2","h3"]
level=
info
ts=
1731183604.7980652
msg=
serving initial configuration
}{   "commitSha": "2d92ac2c88fe26566155f2ded22eebb826b97de3",   "commitUrl": "[https://github.com/appsmithorg/appsmith-ee/commit/2d92ac2c88fe26566155f2ded22eebb826b97de3",](https://github.com/appsmithorg/appsmith-ee/commit/2d92ac2c88fe26566155f2ded22eebb826b97de3%22,)   "githubRef": "refs/tags/v1.48",   "githubRunUrl": "[https://github.com/appsmithorg/appsmith-ee/actions/runs/11740064412/attempts/1",](https://github.com/appsmithorg/appsmith-ee/actions/runs/11740064412/attempts/1%22,)   "version": "v1.48",   "imageBuiltAt": "2024-11-08T10:16:51+00:00",   "isCI": true } Successfully started Caddy (pid=67) - Caddy is running in the background
2024-11-09T20:20:04.805Z Checking environment configuration
2024-11-09T20:20:04.809Z Configuring database connection URL
2024-11-09T20:20:04.812Z Checking APPSMITH_DB_URL
2024-11-09T20:20:04.816Z Detected local DB
2024-11-09T20:20:04.823Z Initializing MongoDB
2024-11-09T20:20:04.830Z Initializing local database
'/appsmith-stacks/data/mongodb/key' -> '/tmp/appsmith/mongodb-key'
2024-11-09T20:20:04.863Z Checking initialized database
2024-11-09T20:20:04.872Z Initializing Replica Set for local database
level=
info
ts=
1731183604.8884215
logger=
tls
msg=
storage cleaning happened too recently; skipping for now
storage=
FileStorage:/appsmith-stacks/data/caddy
instance=
207b4ca0-492b-4358-aedd-5b6fed055558
try_again=
1731270004.888417
try_again_in=
86399.999999294
level=
info
ts=
1731183604.8885655
logger=
tls
msg=
finished cleaning storage units
/opt/appsmith/entrypoint.sh: line 241:   102 Illegal instruction     mongod --fork --port 27017 --dbpath "$MONGO_DB_PATH" --logpath "$MONGO_LOG_PATH"
09/11/2024
20:20:07
Container stopped
````

### Steps To Reproduce

Used the proposed Docker Compose .yml - https://docs.appsmith.com/getting-started/setup/installation-guides/docker

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

Latest

**Comment by agaitan026** [comment]
got same issue here in a new installation

`/opt/appsmith/entrypoint.sh: line 241:    96 Illegal instruction     (core dumped) mongod --fork --port 27017 --dbpath "$MONGO_DB_PATH" --logpath "$MONGO_LOG_PATH"
`

**Comment by Nikhil-Nandagopal** [comment]
@nodecentral @agaitan026 can you tell us whether you tried to install docker / k8s?
Which cloud provider or machine did you try to install on?
Please share your docker-compose file.

**Comment by sharat87** [comment]
Just tried on a new AWS EC2 instance with `uname -a` as below:

```
Linux ip-172-31-2-53 6.8.0-1016-aws #17-Ubuntu SMP Mon Sep  2 13:48:07 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```


And with this `docker-compose.yml`:

```yaml
version: "3"
services:
 appsmith:
   image: index.docker.io/appsmith/appsmith-ee
   container_name: appsmith
   ports:
       - "80:80"
       - "443:443"
   volumes:
       - ./stacks:/appsmith-stacks
   restart: unless-stopped
```

Appsmith starts up fine. Can you share further details on what's different on your systems? The error you're seeing usually comes up when running an AMD image on an ARM system or the other way around. Can you do a `docker image inspect appsmith/appsmith-ee` and share the output please?

**Comment by agaitan026** [comment]
Here's details:

`SUre sure, I will leave you important info here.
So 

VM is type QEMU/KVM
Machine type i440fx
CPU: x86-64-v2-AES
RAM: 4GB
2 Cores

This is standard, linux native KVM virtualization, like openstack, proxmox, virt-manager,xen etc. The most standard of all standards here`

**Comment by gnuhost** [comment]
Good day, Im euronodes.com support guy. To avoid passing the messages through the client, I think it will be best if I answer some questions directly. We are intersted to solve it as well, so our customers can use your system. If there's anything I can help regarding running on KVM/QEMU virtualization, Im all ears

**Comment by gnuhost** [comment]
For anyone having problems with installing on KVM/QEMU - this helped:
- increased RAM to 8GB 
- increased cores to 4GB
- changed CPU type to Host
- enabled NUMA for CPU
- disabled balooning device for RAM

**Comment by nodecentral** [comment]
Still the same situation for me, 

I’m doing a local install, via Docker on a QNAP NAS, (Linux, 16GB RAM) compose is below..

````
version: "3"
services:
   appsmith:
     image: index.docker.io/appsmith/appsmith-ee
     container_name: appsmith
     ports:
         - "808:80"
         - "4434:443"
     volumes:
      - /share/Container/appsmith/stacks:/appsmith-stacks
     restart: unless-stopped
  ````

**Comment by dvision1979** [comment]
Same experience here, on QNAP docker:
`102 Illegal instruction     mongod --fork --port 27017 --dbpath "$MONGO_DB_PATH" --logpath "$MONGO_LOG_PATH"`

**Comment by sharat87** [comment]
Looks like it's failing in starting MongoDB server in all cases. I haven't been able to reproduce this (probably lack of the type of system that's facing this), but can we try with an external MongoDB instead? Like, provision a MongoDB instance on MongoDB Atlas, and use that instead? In that case Appsmith Docker container won't attempt to start the embedded MongoDB at all.

[Documentation on using an external MongoDB](https://docs.appsmith.com/getting-started/setup/instance-configuration/custom-mongodb-redis#external-mongodb).

**Comment by ravir2m2** [comment]
I had the exact same issue as well running docker setup locally on my Macbook Pro laptop. I made a change to the docker-compose file so that AppSmith can use a different Mongo container and Redis to make it work. The following are the changes made, hopefully it helps you 

## Docker-Compose file
```
services:
  mongo:
    image: mongo:latest
    container_name: appsmith-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init/init-0.js:/docker-entrypoint-initdb.d/init-0.js # Add this line to initialize the database
    command: ["mongod", "--replSet", "rs0"] # Enable replica set      
    restart: always
    networks:
      - appsmith_network
      
  redis:
    image: redis:latest
    container_name: appsmith-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: ["redis-server", "--appendonly", "yes"] # Enable persistence
    networks:
      - appsmith_network

  appsmith:
    image: appsmith/appsmith-ee:release
    platform: linux/amd64  # Add this line to enable emulation for Macbook
    container_name: appsmith
    environment:
      APPSMITH_MONGODB_URI: mongodb://mongo:27017/appsmith
      APPSMITH_DB_URL: mongodb://mongo:27017/appsmith
      APPSMITH_REDIS_URL: redis://redis:6379
      APPSMITH_MAIL_ENABLED: false
      APPSMITH_ENCRYPTION_PASSWORD: supersecretpassword
      APPSMITH_ENCRYPTION_SALT: supersecretsalt     
      APPSMITH_HOSTNAME: "0.0.0.0"
      APPSMITH_SERVER_PORT: 80 
      APPSMITH_DISABLE_TELEMETRY: true
    depends_on:
      - mongo
      - redis
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - stacks:/appsmith-stacks
    restart: unless-stopped
    networks:
      - appsmith_network    
          
volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  stacks:
    driver: local

networks:
  appsmith_network:
    driver: bridge      
```

## ./mongo-init/init-0.js file

```
// init.js
try {
    console.log('######### Initializing Replica Set #########');
    rs.initiate();
} catch (err) {
    console.error(err);
} finally {
    console.log('######### Successfully initialized Replica Set #########');
}

```
