### ISSUE TITLE
[Bug]: mongodb replicaset key is not fixed, changing on each "helm template", resulting on "AuthenticationFailed: SCRAM authentication failed, storedKey" after a while

### ISSUE THREAD

**Issue by damienleger** [appsmithorg/appsmith#38432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On values.yml file currently, mongodb.auth.replicaSetKey is not fixed (value on bitnami helm chart: https://github.com/bitnami/charts/blob/343ce6df75c858132b0a42cb7691441da56768df/bitnami/mongodb/values.yaml#L198). Hence, on each "helm template" invocation, the value of the "mongodb-replica-set-key" key in appsmith-mongodb Secret changes. Such invocation is done by ArgoCD on regular basis, or I suppose every time a deployment takes place with "vanilla" helm, ultimately causing mismatch of replicaset key betweens the differents mongodb containers and the error "AuthenticationFailed: SCRAM authentication failed, storedKey" during the lifecycle of mongodb and eventually a mongodb that refuses to start at all.

### Steps To Reproduce

1. Invoke `helm template` twice and notice the only diff is on the "mongodb-replica-set-key" key in appsmith-mongodb Secret. Something like `diff <(helm template .) <(helm template .)` in bash

2. And you can simulate the behavior of ArgoCD by `kubectl apply` the result of `helm template .` on a fresh appsmith install. Notice envvar in mongodb container now matches the Secret that is why it's working on fresh install. `kubectl apply` once or twice the result of `helm template .` and randomly restart mongodb containers in between. You should see the error "AuthenticationFailed: SCRAM authentication failed, storedKey" in the logs of mongodb

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

ee chart appsmith-3.4.5

**Comment by wyattwalter** [comment]
Hi @damienleger, normally during a Helm installation, Helm would store those randomly generated in the cluster so it could be used in subsequent upgrades and would not be a problem.

But ArgoCD breaks this model because it, as you indicated, runs a `helm template` and uses the results to diff / apply resources to the cluster. A couple of workaround for now:

- You could set `mongodb.auth.replicaSetKey` to a static value
- Use ArgoCD's ignoreDifferences feature to have ArgoCD not apply new values every time (add `RespectIgnoreDifferences=true` to syncOptions  and then set the `ignoreDifferences` key. Example:

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appsmith
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://helm-ee.appsmith.com'
    targetRevision: "3.6.0"
    chart: appsmith
    helm:
      values: |
        ....
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: appsmith
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
  - kind: Secret
    name: appsmith-mongodb
    jsonPointers:
    - /data/mongodb-replica-set-key
```

Once either method is applied you'll likely have to restart the MongoDB statefulsets in ArgoCD.
