### ISSUE TITLE
[Bug]: Appsmith-EE helm chart refers to non-existing non-root user and group

### ISSUE THREAD

**Issue by ssichynskyi** [appsmithorg/appsmith#38787]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

In Appsmith-EE values.yaml there are 2 blocks instructing the user on how to run under non-root:
```yaml
podSecurityContext: {}
  # For non-root user
  #  fsGroup: 1001
  #  sysctls:
  #  - name: net.ipv4.ip_unprivileged_port_start
  #    value: "80"
securityContext: {}
  # For non-root user
  # runAsNonRoot: true
  # runAsUser: 1000
```
When I uncomment them and use like this:
```yaml
    # ....
    helm:
      releaseName: appsmith-ee
      values: |-
        # ....
        podSecurityContext:
          fsGroup: 1001
          sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: "80"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
```
However has nor /etc/passwd on appsmith container is not aware about user with ID 1000.
When SSH in appsmith, the prompt is as follows:
```
groups: cannot find name for group ID 1001
I have no name!@appsmith-ee-0:/opt/appsmith$ ...
```

### Steps To Reproduce

1. Deploy the Appsmith-EE on k8s using the most recent helm chart (3.6.0) using abovementioned configs
2. SSH into the appsmith pod

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Helm chart 3.6.0.
