### ISSUE TITLE
[Bug]: Alloy errors/crash when Appsmith-EE is run under non-root user

### ISSUE THREAD

**Issue by ssichynskyi** [appsmithorg/appsmith#39911]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

If Appsmith-ee is configured to run under non-root user, Alloy cannot make directory that it require in order to run, which results in the following logs:
```
appsmith 2025-03-11 08:37:44,671 INFO success: alloy entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
appsmith alloy stderr | Error: failed to create the remotecfg service: mkdir data-alloy: permission denied
appsmith 2025-03-11 08:37:44,674 INFO exited: alloy (exit status 1; not expected)
```
which is repeated endlessly with a frequency of ~1-2 per second.

Initial source: https://github.com/appsmithorg/appsmith/issues/38787#issuecomment-2713440132
Related issue: https://github.com/appsmithorg/appsmith/issues/38787

### Steps To Reproduce

1. Install Appsmith-EE in k8s using helm chart (latest version, but it seems like the issue was more-or-less always there). Configure Appsmith-EE to run under non-root user in `values.yaml`:
```
        podSecurityContext:
          fsGroup: 1001
          sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: "80"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
```

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Helm chart 3.6.0+
