### ISSUE TITLE
[Bug]: MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017

### ISSUE THREAD

**Issue by masterbalby2** [appsmithorg/appsmith#40908]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

I can't get appsmith to work using docker on a synology SA6400.
The error `MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017` appears regularly. 

The container doesn't stop, but I can't access the form for creating the first account.
I end up on a blank page with the Appsmith logo in the top left-hand corner.

### Steps To Reproduce

```
services:
  appsmith:
    image: appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "80:80"
      - "443:443"
    environment:
      APPSMITH_SIGNUP_DISABLED: "false"
    restart: unless-stopped
```

[appsmith-2025-06-10T06-45-42.log](https://github.com/user-attachments/files/20666760/appsmith-2025-06-10T06-45-42.log)

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

Self hosted - latest
