### ISSUE TITLE
[Bug] Arabic characters in Google sheets

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#7835]
## Description

From Intercom:
Hey there, I'm having some trouble reading data from a google sheet that contains Arabic letters, everything comes back as question marks. Is there any special setup I need to do to make this work? Thanks!

**Comment by tawakol** [comment]
A bit more detail: 

I had an appsmith instance set up via Digital Ocean one-click apps, that worked absolutely fine for arabic. 

I decided to run a custom instance with Docker and I imported by same app, now Arabic no longer works. I'm using the Google Sheets integration as a data source. 

Here's a link to a sheet containing arabic: 

https://docs.google.com/spreadsheets/d/17md7MIa0yQHiTLKxlMsRKG5zzY0rZkCuT0gTT007UlM/edit?usp=sharing

Thanks!

Here's a

**Comment by nidhi-nair** [comment]
Hey @tawakol, when you say you're running a custom instance with Docker, could you please specify how you've brought this new instance up?

**Comment by tawakol** [comment]
Sure, I followed the steps for the 'Long Start' with the docker-compose.yml at this link: 

https://docs.appsmith.com/setup/docker

**Comment by nidhi-nair** [comment]
@tawakol Ah I see, I have been able to reproduce this. Let me try to RCA this issue and get back to you.

**Comment by nidhi-nair** [comment]
@tawakol This was an issue with the Docker image we were using in the link you provided, we have fixed this now and the new image should be created with our next release. If you would like a quick fix to the issue let me know and I can work with you for a work around.

**Comment by nidhi-nair** [comment]
I'm closing this issue since a fix will be available in the next release. If there are any immediate concerns about this issue, please drop a comment here and I'll reopen it.

**Comment by tawakol** [comment]
Hey @nidhi-nair, if a workaround is available that would be fantastic. Please let me know.

**Comment by nidhi-nair** [comment]
@tawakol You basically want to add a couple of environment variables to the docker-compose file. So in this piece of configuration for the appsmith service:
```
appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "80:80"
      - "443:443"
      - "9001:9001"
    volumes:
      - ./stacks:/appsmith-stacks
    labels:
      com.centurylinklabs.watchtower.enable: "true"
```

Add the following environment variables as shown. You can simply replace the above snippet with the one below:
```
appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "80:80"
      - "443:443"
      - "9001:9001"
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    volumes:
      - ./stacks:/appsmith-stacks
    labels:
      com.centurylinklabs.watchtower.enable: "true"
```

After updating these variables, you'll need to restart the containers as well.
