### ISSUE TITLE
[Bug]: When Appsmith is hosted on Kubernetes cluster with Istio enabled, server fails to communicate with Mongo and Redis    

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#9925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The user tried to self-host Appsmith on the Kubernetes cluster with Istio enabled, but failed to get it running because the server was not able to communicate with the mongo and redis. But when Istio was disabled everything works as expected.  

### Steps To Reproduce

1. Use kubernetes cluster to host Appsmith
2. Enable Istio deployment 
3. Check error  

### Environment

Production

### Version

Self-Hosted

**Comment by pcostesi** [comment]
I managed to get past the `initContainers` using the following values for the community chart:

```yaml
podAnnotations:
  traffic.sidecar.istio.io/excludeInboundPorts: "6379,27017,15020"
  traffic.sidecar.istio.io/excludeOutboundPorts: "6379,27017,15020"
  proxy.istio.io/config: |
    proxyMetadata:
      ISTIO_META_DNS_CAPTURE: "false"
      ISTIO_META_DNS_AUTO_ALLOCATE: "false"
```

This leaves Istio installed (we are running Istio and Istio-CNI), but side-steps the iptable routes for Redis and Mongo. Additionally, it also disables the DNS capture and auto-allocation, which requires the `istio-proxy` container.
